name: linuxserver-webtop-xfce
services:
  app:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $Europe/Stockholm
      SUBFOLDER: ''
      TITLE: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: Europe/Stockholm
          description:
            en_us: specify a timezone to use, see this list.
        - container: SUBFOLDER
          description:
            en_us: Specify a subfolder to use with reverse proxies, IE /subfolder/
        - container: TITLE
          description:
            en_us: String which will be used as page/tab title in the web browser.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webtop/config
        target: /config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: 'https://docs.linuxserver.io/images/docker-webtop/#supported-architectures'
  tagline:
    en_us: Alpine, Ubuntu, Fedora, and Arch based containers containing full desktop environments in officially supported flavors accessible via any modern web browser.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/webtop-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/webtop-logo.png
  title:
    en_us: Webtop
  category: LinuxServer.io
  project_url: https://github.com/linuxserver/docker-webtop
  port_map: '3000'
